/* Generated By:JJTree: Do not edit this line. ASTConversationTopLevel.java */

package conversation.parser;

public class ASTConversationTopLevel extends ParseNode {
  public ASTConversationTopLevel(int id) {
    super(id);
  }

  public ASTConversationTopLevel(Parser p, int id) {
    super(p, id);
  }

}
