/* Generated By:JJTree: Do not edit this line. ASTGroupNode.java */
package conversation.parser;

import java.util.ArrayList;
import java.util.List;

public class ASTGroupNode extends ParseNode implements GroupContents {

    public static final GroupContents BEAT_BREAK = new GroupContents() {
    };
    public static final GroupContents TOPIC_BREAK = new GroupContents() {
    };
    private List<GroupContents> contents = new ArrayList<GroupContents>();
    private String type;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void addLeaf(ASTLeafNode leaf) {
        contents.add(leaf);
    }

    public void addGroup(ASTGroupNode group) {
        contents.add(group);
    }

    public void addBeatBreak() {
        contents.add(BEAT_BREAK);
    }

    public void addTopicBreak() {
        contents.add(TOPIC_BREAK);
    }

    public List<GroupContents> getContents() {
        return contents;
    }

    public ASTGroupNode(int id) {
        super(id);
    }

    public ASTGroupNode(Parser p, int id) {
        super(p, id);
    }
}
