/* Generated By:JJTree: Do not edit this line. ASTLeafNode.java */
package conversation.parser;

public class ASTLeafNode extends ParseNode implements GroupContents {

    private String speaker;
    private String content;

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getSpeaker() {
        return speaker;
    }

    public void setSpeaker(String speaker) {
        this.speaker = speaker;
    }

    public ASTLeafNode(int id) {
        super(id);
    }

    public ASTLeafNode(Parser p, int id) {
        super(p, id);
    }
}
