/* Generated By:JJTree: Do not edit this line. ASTTopicNode.java */
package conversation.parser;

import java.util.ArrayList;
import java.util.List;

public class ASTTopicNode extends ParseNode {

    private boolean starting;
    private List<ASTBeatNode> beats = new ArrayList<ASTBeatNode>();
    private String name;

    public void setStarting(boolean starting) {
        this.starting = starting;
    }

    public boolean isStarting() {
        return starting;
    }

    public List<ASTBeatNode> getBeats() {
        return beats;
    }

    public void addBeat(ASTBeatNode beatNode) {
        beats.add(beatNode);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ASTTopicNode(int id) {
        super(id);
    }

    public ASTTopicNode(Parser p, int id) {
        super(p, id);
    }
}
