/* Generated By:JJTree: Do not edit this line. C:\Projects\ConversationAPI\src\conversation\parser\ParserTreeConstants.java */

package conversation.parser;

public interface ParserTreeConstants
{
  public int JJTCONVERSATIONTOPLEVEL = 0;


  public String[] jjtNodeName = {
    "ConversationTopLevel",
  };
}
