/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package conversation.parser;

public interface ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int INTEGER_LITERAL = 13;
  int DECIMAL_LITERAL = 14;
  int HEX_LITERAL = 15;
  int OCTAL_LITERAL = 16;
  int FLOATING_POINT_LITERAL = 17;
  int EXPONENT = 18;
  int CHARACTER_LITERAL = 19;
  int STRING_LITERAL = 20;
  int CONVERSATION = 21;
  int PARTICIPANT = 22;
  int IDENTIFIER = 23;
  int LETTER = 24;
  int DIGIT = 25;
  int LPAREN = 26;
  int RPAREN = 27;
  int LBRACE = 28;
  int RBRACE = 29;
  int LBRACKET = 30;
  int RBRACKET = 31;
  int SEMICOLON = 32;
  int COMMA = 33;
  int DOT = 34;
  int AT = 35;
  int ASSIGN = 36;
  int LT = 37;
  int BANG = 38;
  int TILDE = 39;
  int HOOK = 40;
  int COLON = 41;
  int EQ = 42;
  int LE = 43;
  int GE = 44;
  int NE = 45;
  int SC_OR = 46;
  int SC_AND = 47;
  int INCR = 48;
  int DECR = 49;
  int PLUS = 50;
  int MINUS = 51;
  int STAR = 52;
  int SLASH = 53;
  int BIT_AND = 54;
  int BIT_OR = 55;
  int XOR = 56;
  int REM = 57;
  int LSHIFT = 58;
  int PLUSASSIGN = 59;
  int MINUSASSIGN = 60;
  int STARASSIGN = 61;
  int SLASHASSIGN = 62;
  int ANDASSIGN = 63;
  int ORASSIGN = 64;
  int XORASSIGN = 65;
  int REMASSIGN = 66;
  int LSHIFTASSIGN = 67;
  int RSIGNEDSHIFTASSIGN = 68;
  int RUNSIGNEDSHIFTASSIGN = 69;
  int ELLIPSIS = 70;
  int RUNSIGNEDSHIFT = 71;
  int RSIGNEDSHIFT = 72;
  int GT = 73;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"conversation\"",
    "\"participant\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
