/* Generated By:JJTree: Do not edit this line. ASTConversationTopLevel.java */
package conversation.parser;

import java.util.ArrayList;
import java.util.List;

public class ASTConversationTopLevel extends ParseNode {

    private String name;
    private List<String> participants = new ArrayList<String>();
    private List<ASTTopicNode> topics = new ArrayList<ASTTopicNode>();

    public String getName() {
        return name;
    }

    public List<String> getParticipants() {
        return participants;
    }

    public List<ASTTopicNode> getTopics() {
        return topics;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void addParticipant(String participant) {
        participants.add(participant);
    }

    public void addTopic(ASTTopicNode topicNode) {
        topics.add(topicNode);
    }

    public ASTConversationTopLevel(int id) {
        super(id);
    }

    public ASTConversationTopLevel(Parser p, int id) {
        super(p, id);
    }
}
