/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package conversation.parser;

public interface ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int INTEGER_LITERAL = 13;
  int DECIMAL_LITERAL = 14;
  int HEX_LITERAL = 15;
  int OCTAL_LITERAL = 16;
  int FLOATING_POINT_LITERAL = 17;
  int EXPONENT = 18;
  int CHARACTER_LITERAL = 19;
  int STRING_LITERAL = 20;
  int CONVERSATION = 21;
  int PARTICIPANT = 22;
  int STARTING = 23;
  int TOPIC = 24;
  int BEAT = 25;
  int NODE = 26;
  int OP = 27;
  int SEQ = 28;
  int BREAK = 29;
  int END = 30;
  int WHEN = 31;
  int SET = 32;
  int CLEAR = 33;
  int IDENTIFIER = 34;
  int LETTER = 35;
  int DIGIT = 36;
  int LPAREN = 37;
  int RPAREN = 38;
  int LBRACE = 39;
  int RBRACE = 40;
  int LBRACKET = 41;
  int RBRACKET = 42;
  int SEMICOLON = 43;
  int COMMA = 44;
  int DOT = 45;
  int AT = 46;
  int ASSIGN = 47;
  int LT = 48;
  int BANG = 49;
  int TILDE = 50;
  int HOOK = 51;
  int COLON = 52;
  int EQ = 53;
  int LE = 54;
  int GE = 55;
  int NE = 56;
  int SC_OR = 57;
  int SC_AND = 58;
  int INCR = 59;
  int DECR = 60;
  int PLUS = 61;
  int MINUS = 62;
  int STAR = 63;
  int SLASH = 64;
  int BIT_AND = 65;
  int BIT_OR = 66;
  int XOR = 67;
  int REM = 68;
  int LSHIFT = 69;
  int PLUSASSIGN = 70;
  int MINUSASSIGN = 71;
  int STARASSIGN = 72;
  int SLASHASSIGN = 73;
  int ANDASSIGN = 74;
  int ORASSIGN = 75;
  int XORASSIGN = 76;
  int REMASSIGN = 77;
  int LSHIFTASSIGN = 78;
  int RSIGNEDSHIFTASSIGN = 79;
  int RUNSIGNEDSHIFTASSIGN = 80;
  int ELLIPSIS = 81;
  int RUNSIGNEDSHIFT = 82;
  int RSIGNEDSHIFT = 83;
  int GT = 84;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"conversation\"",
    "\"participant\"",
    "\"starting\"",
    "\"topic\"",
    "\"beat\"",
    "\"node\"",
    "\"op\"",
    "\"seq\"",
    "\"break\"",
    "\"end\"",
    "\"when\"",
    "\"set\"",
    "\"clear\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
